language: python
python:
- '3.4'
services:
- docker
env:
  global:
  - DOCKER_REPO=gmrukwa/divik
  - MAJOR=1
  - MINOR=13
  - FIXUP=8
  - secure: D58HyiO9DVKYGIjVcp0mNbLCvZ0BrQ8VtJ+74WXAIDTY4N5L4yGnAP4BGOhtcjFxD9calruRuBmSBMe2TCJAjkmG9KWPkyXNeN7B9T8spTuTyBybW2Xd9MEUTruXkr49W3zic7L1kecq8FGlO7k9Cc4VRl0KPjps3AAKdRmWi87g3flrDhTeODpOYNFBlfhoH8lcXs1dwUs7aNtbL5SIBnc+rpOYWnZ8TUpynkKjtQnmkixXBySdmHZQOAugpmeWX43slyt5Z3VCfTEqxDsk9uD2xmVF2rmMXSKXTorGPqx7AXrsvCHUUb0W+C3z1LfcPeUW0DrBWkksph0twYnxnxcE7hxpxQm1SQPz6pIzBZ3TUiYpvP+qTdKrIDvR8hnE8wEvsVCBxNYVCf0/BjUoUu7OTSTMdWvPGtcC81WBpizFPeVEYRf8MRY0Ug45N3EdJ7TJ6Xtlm/UaefazKsdDrDc0nD7rXj9zSsOeZezC8Hk51E2n+/lDbdllXiNUbBQs4T+1JyoM3qJP4o4+A20uP4frkqmIBetCC+RGBS1d/oEUdm+gXZ1pZvgt9uujRSgAFjbdAAhCDwUOpUI9CGGJB34gZFWF81ztU4SSH2/8zHTrxzz19u0chTNj+rG5T0+02c4pJEi9b5cYJZ7aYh51iRWGI4hjDEPdl1unEP6rwSc=
  - secure: m2vvWHoICkFSR34Yt/l+mDZn0X803vcCy0Xu9NDUnFE6CipNR0PIq2EJhud7kmhN0/QjwXQ7yldLQRGhMLLF6uoRo6TSGnhREpRIZvyT7Pa9aG9irdzX6sWJha4PbZJtXJvG2AqPH6ZExhH8KAqawd24g4o9aiq1Z2c9fC4vRAKeXNm86YPR+8NMoBARgU/bU9Tn9VdegO/KrZfmsD3h5DbnZrRfD7oKroGsrq4g/f7trkWeI88G2qKol+HtfQfxjCTDN490nNmAywYlYzDcodv0fkcCNovWlAZLpHn4450EmJ4PuNKi9phgKYKDqWWZxQx23MaasKG/UFCx/GI2ZLjEE4NNtNpV4QSREB2knwC0s/UCA+XH6zx0dMfWuDAH00au94NfntCiWi+Hei/jAKPgtiSOsttePuCoe8BJbisTai3kA9olU/MX32DTX9UEzobVsvK86ECERVMwkzjWbPvIg9QMTyZk6S7KHuAbUvOlv5PVADAwZsh8NG56lbn6hopkJRMcAhC4JerkSJ2RooZFG11giz7Vbxdm6AsoKI3bnNUr7n46lJuacl5X2+tSk4hd7F9GHEUpDX0Cb3bp0ULlL8X4sBeI0D+YfLkvIh+DhzcXG98XpFpQo/o9nz3SbkD7rCPcT+96gANi8ryCCu0GfXa+yipDwCNfNxWAPI0=
install:
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
script:
- |
  if [ $TRAVIS_BRANCH = "master" ]; then
      STAGE=
  elif [ $TRAVIS_BRANCH = "develop" ]; then
      STAGE=beta
  else
      STAGE=alpha
  fi

  set -e

  docker build -t $DOCKER_REPO:latest \
               -t $DOCKER_REPO:beta \
               -t $DOCKER_REPO:$MAJOR.$MINOR.$FIXUP${STAGE:+-$STAGE} \
               -t $DOCKER_REPO:$MAJOR.$MINOR${STAGE:+-$STAGE} \
               -t $DOCKER_REPO:$MAJOR${STAGE:+-$STAGE} \
               .
  docker images
  if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      docker push $DOCKER_REPO:$MAJOR.$MINOR.$FIXUP${STAGE:+-$STAGE}
      docker push $DOCKER_REPO:$MAJOR.$MINOR${STAGE:+-$STAGE}
      docker push $DOCKER_REPO:$MAJOR${STAGE:+-$STAGE}
      if [ $TRAVIS_BRANCH = "master" ]; then
          docker push $DOCKER_REPO:latest
      elif [ $TRAVIS_BRANCH = "develop" ]; then
          docker push $DOCKER_REPO:beta
      fi
  fi
notifications:
  webhooks:
    urls:
      secure: rKvrMuduiL7urmt7aohh+DP/sOzuQw3/y5PJlWyIGDsvZmBHNpRFtSldDIJer5Z5wzkzPdwbQqvpCwGeZLmUI+JG23H/+5sUaVo57ir8c0cIIQgqTz460lvPWk37WKRcGVnBKngtbw6gxhPWMQRLFFxcLxdXoMUBE0ju0mKMBTmbCscNTC1FjQ1enyIiiidWFCY6zx0xwj7gTEKEn5xiAFVSjVTeFCUlIdTiwIwbEtePTFXnEfjpRsX8fcZ35SX/xk0gsIBFwr97y+WdmBNzXCD8VDzpf3gWo6yHE4mcVzwPw0Fbo9YqhugagSP3fPmO3H/Cxuyl090XR2TMT5ETaRj2g7C2hGTp4bGfq/6e+nF6hjvIQlx1REIn2aeFXZGafSzzzrJcqAYYn3bu07w/7tE2MIXTih8o3T1BC0l5LypBtakVKji63c1fReQhW/iZSfCKUewAI1NxzL9w84V16JaKlJOmBsn4CCpklXHIMALZCOZYVeGuu3XlGLRyo5sX7ot95n8Ts7JbhccIwCTwN1Ln5fkna/udEkFF4ibTjsjfrYEt/OWS8JpHZC+qRUMrIG0A6BnrfZRHdEHPSBNsIZZPvDPQBvo728tapfKRfFGRtRzlV8fnNJcSQT/YWT+o1bQJPYiCx04jcPLv1wYCxYIBIQ5EfkcfvwFCysTFdqg=
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
