name: Build and push deployment images

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - develop
  schedule:
    - cron: '0 17 * * *'


env:
  MAJOR: ${{ 2 }}
  MINOR: ${{ 0 }}
  FIXUP: ${{ 0 }}
  DOCKER_REPO: ${{ 'gmrukwa/divik' }}
  IS_ALPHA: ${{ github.event_name == 'pull_request' }}
  IS_BETA: ${{ github.event_name == 'push' && endsWith(github.event.ref, 'heads/develop') }}


jobs:
  push_images:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Authenticate to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: Embed version to package
        run: |
          if $IS_ALPHA; then
            SUFIX=a
          elif $IS_BETA; then
            SUFIX=b
          fi
          echo "__version__ = \"${MAJOR}.${MINOR}.${FIXUP}${SUFIX:+$SUFIX}\"" > divik/__init__.py
          cat divik/__init__.py
      - name: Build image
        run: |
          docker build \
            --file docker/deploy.dockerfile \
            --tag deployment \
            .
      - name: Push annotated images
        run: |
          if $IS_ALPHA; then
            STAGE=alpha
          elif $IS_BETA; then
            STAGE=beta
          fi
          echo "STAGE=$STAGE"
          docker tag deployment $DOCKER_REPO:$MAJOR.$MINOR.$FIXUP${STAGE:+-$STAGE}
          docker tag deployment $DOCKER_REPO:$MAJOR.$MINOR${STAGE:+-$STAGE}
          docker tag deployment $DOCKER_REPO:$MAJOR${STAGE:+-$STAGE}
          docker push $DOCKER_REPO:$MAJOR.$MINOR.$FIXUP${STAGE:+-$STAGE}
          docker push $DOCKER_REPO:$MAJOR.$MINOR${STAGE:+-$STAGE}
          docker push $DOCKER_REPO:$MAJOR${STAGE:+-$STAGE}
      - name: Push latest image for master branch
        if: github.event_name == 'push' && endsWith(github.event.ref, 'heads/master')
        run: |
          docker tag deployment $DOCKER_REPO:latest
          docker push $DOCKER_REPO:latest
